on: [push, pull_request]

name: Continuous integration

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.10.7'
          cabal-version: '3.6.2.0'
      - run: cabal test
